initial_url: "https://airpassengerrights.ca/en/practical-guides/baggage/damage/step-by-step-guide"
query_keywords:
  - "Delay"
  - "Cancellation"
  - "Lost"
  - "Damaged"
  - "Delayed"
  - "Denied boarding"
  - "Flight issues"
  - "Baggage issues"
  - "Denied boarding"
  - "law"
  - "regulation"
  - "compensation"
  - "rights"
  - "air passenger rights"
  - "issue"
  - "problem"
  - "Compensation"
  - "complain"
